name: MakeThis
favicon: null
layout_spectrum: 1
typography_spectrum: 0.48614
title: design studio
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#010504'
    - '#e9edec'
    - '#2d6376'
    - '#719eb1'
    - '#dab352'
  brandStrength: 0.6875
  lightness: 0.43010710435919464
  saturation: 0.8125
  rhythmicContrast: 0.5
purpose: []
