name: MakeThis
favicon: null
layout_spectrum: 0.7909738083835691
typography_spectrum: 0.72133
title: design studio
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#b9d4f3'
    - '#006fc5'
    - '#000000'
    - '#56a4e4'
    - '#ff9818'
  brandStrength: 0.6875
  lightness: 0.43010710435919464
  saturation: 0.8827303336001933
  rhythmicContrast: 0.5770034268498421
purpose: []
